[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_voting = "ABTDuP27AJX7ZDcSFcqcEYt86aC9M19EjQ4vDn6KLcZw"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/akshatsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
