[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_voting = "2FCNqcTDHfNSHKGCj33DRbkgNJkW62JJswtz6X47iCRQ"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/akshatsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
