[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
zk_voting = "EoUv2UHa4y25Vm3opdDZGyfMbgEZ5DF7PaUTdHB2PLrM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Devnet"
wallet = "/Users/akshatsharma/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
